#include "../hook/detour.h"

#if _WIN64
using Detour = Detour64;
	#define MESSAGEBOXAPATCHSIZE 14
	#define DEFAULTPATCHSIZE 15
	#define SELECT_PATCHSIZE 15
	#define IOCTLSOCKET_PATCHSIZE 16
    #define CLOSEPATCHSIZE 14
	#define WSASOCKETA_PATCHSIZE 19
#else
using Detour = Detour32;
	#define MESSAGEBOXAPATCHSIZE 5
	#define DEFAULTPATCHSIZE 5
	#define SELECT_PATCHSIZE 7
	#define IOCTLSOCKET_PATCHSIZE 5
	#define CLOSEPATCHSIZE 5
	#define WSASOCKETA_PATCHSIZE 5
#endif
