#if _WIN64
	#define DETOUR Detour64
	#define MESSAGEBOXAPATCHSIZE 14
	#define SENDPATCHSIZE 15
    #define CLOSEPATCHSIZE 15
#else
	#define DETOUR Detour32
	#define MESSAGEBOXAPATCHSIZE 5
	#define SENDPATCHSIZE 5
	#define CLOSEPATCHSIZE 5
#endif
