namespace XOPE_UI.Model
{
    public enum SpyMessageType
    {
        INVALID_MESSAGE,
        PING,
        PONG,
        ERROR_MESSAGE,
        INJECT_SEND,
        INJECT_RECV,
        CLOSE_SOCKET,
        IS_SOCKET_WRITABLE,
        REQUEST_SOCKET_INFO,
        TOGGLE_HTTP_TUNNELING,
        STOP_HTTP_TUNNELING_SOCKET,
        ADD_PACKET_FITLER,
        MODIFY_PACKET_FILTER,
        TOGGLE_ACTIVATE_FILTER,
        DELETE_PACKET_FILTER,
        JOB_RESPONSE_SUCCESS,
        JOB_RESPONSE_ERROR,
        SHUTDOWN_RECV_THREAD
    }
}
